from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel, Field


class AuthorIn(BaseModel):
    name: str = Field(description="Author's display name")
    twitter: Optional[str] = Field(default=None, description="Author's Twitter handle")
    avatarUrl: Optional[str] = Field(default=None, description="URL to avatar image")


class PostIn(BaseModel):
    slug: Optional[str] = Field(default=None, description="URL-friendly slug; autogenerated if missing")
    title: str = Field(description="Post title")
    summary: Optional[str] = Field(default=None, description="Short summary")
    contentHtml: str = Field(description="Post body in semantic HTML")
    date: Optional[str] = Field(default=None, description="ISO date-time string")
    image: Optional[str] = Field(default=None, description="Hero image URL")
    readingTimeMinutes: Optional[int] = Field(default=None, description="Estimated reading time in minutes")


class PostBundle(BaseModel):
    post: PostIn
    tags: List[str] = []
    authors: List[AuthorIn] = []
